export const WIDTH_NODE = 100;
export const HEIGHT_NODE = 50;

export const INDENT_LEFT_MAIN_NODE = 200;
export const INDENT_LEFT_FROM_NODE = 0;
export const INDENT_LEFT_TO_NODE = 400;
export const INDENT_BOTTOM_ALL_NODE = 10;

export const HEIGHT_WITH_BOTTOM_INDENT_NODE = HEIGHT_NODE + INDENT_BOTTOM_ALL_NODE;
export const CANVAS_HEIGHT = 100;
export const CANVAS_WIDTH = 100;
export const DIAGRAM_CONTAINER_HEIGHT_COLLAPSE = 300;
export const DIAGRAM_CONTAINER_HEIGHT_EXPANDED = 500;