version: 0.0
os: linux
files:
  - source: dfmui.zip
    destination: /var/www/
    runas: root
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: root

